---
# tasks file for docker
- name: Install required packages
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    state: present
    update_cache: yes
    
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker

- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: 
    - docker-ce
    - containerd.io 
    - docker-ce-cli
    state: present
    update_cache: yes
  notify:
  - docker service start

- name: Add current user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: creating dir
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    recurse: yes

- name: Create daemon json config file
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  tags:
  - file
  notify:
  - daemon reload
  - docker service start
