pipeline {
    agent any 

    environment {
        image = "arpitdoc/nginx-test"
    }

    stages {
        stage('Build') {
            steps {
                script {
                    dir('Jenkins/cicd') {
                        sh 'echo "BUILD STAGE"'
                        sh 'whoami'
                        sh 'ls'
                        sh 'pwd'
                        dockerImage  = docker.build("$image:$BUILD_NUMBER")
                    }  
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'echo "Test STAGE"'
                    dockerImage.inside() {
                        sh 'cat /usr/share/www/html/index.html'
                    }
                }
            }
        }

        stage('Push') {
            steps {
                script {
                    sh 'echo "Push STAGE"'
                }
            }
        }
    }
}