pipeline {
    agent any

    environment {
        registry = "arpitdoc/nginx-sample"
        registryCredentials = 'dockerhub'
    }

    stages {
        stage('Build') {
            steps {
                script {
                    dir('Jenkins/docker-CICD') {
                        sh 'ls && pwd'
                        sh 'echo "${registry}"'        
                        dockerImage = docker.build("${registry}:${BUILD_NUMBER}")
                    }
                }
            }
        }

        stage('Push') {
            steps {
                script {
                    withDockerRegistry(credentialsId: registryCredentials) {
                        dockerImage.push()
                    }
                }
            }
        }   
    }
}