---
 - name: Document Root exist
   file:
     path: "/var/www/{{ key_name }}"
     mode: "0755"
     owner: root
     state: directory
 - name: Index pages are set
   template:
     src: "index.html.j2"
     dest: "/var/www/{{ key_name }}/index.html"
 - name: SELinux policy is correct for web site location3
   sefcontext:
     target: '/var/www(/.*)?'
     setype: httpd_sys_content_t
     state: present
 - name: Correct SELinux file context is on web content4
   file:
     path: /var/www
     state: directory
     recurse: yes
     follow: no
     setype: _default

 - name: Ensuring tls directory exists
   file:
     path: /etc/pki/tls/
     recurse: true
     state: directory

 - name: Ensuring certs and key directory exists
   file:
     path: "/etc/pki/tls/{{ item }}"
     state: directory
   loop: 
   - certs
   - private  
  
 - name: Virtual host TLS certs in place5
   copy:
     src: "{{ path }}/{{ key_name }}.key"
     dest: "/etc/pki/tls/private"
     remote_src: true
 - name: Virtual host TLS private keys in place
   copy:
     src: "{{ path }}/{{ domain }}.crt"
     dest: "/etc/pki/tls/certs"
     remote_src: true
