---
# tasks file for kubeadm
 - name: Getting Total memory
   ansible.builtin.debug:
     msg: "Total memory in Mi: {{ ansible_facts.memtotal_mb }}"

 - fail:
     msg: "Memory not sufficient, Machine should have atleast 4GB Memory"
   when:  ( ansible_facts.memtotal_mb | int ) < 3877

 - name: Getting cpu cores
   ansible.builtin.debug:
     msg: "Total core: {{ ansible_facts.processor_count }}"

 - fail:
     msg: "CPU not sufficient, Machine should have atleast 2 cpu cores"
   when:  ( ansible_facts.processor_count | int ) < 2