---
 - name: Installing kubeadm
   hosts: localhost
   pre_tasks:
   - name: pinging host
     ansible.builtin.ping:

   roles:
   - role: pre-check
     become: false

#   - role: basic-config
#     become: true
#
#   - role: crio
#     become: true    
#
#   - role: kubeadm
#     become: true
   