---
 - name: Disable SWAP since kubernetes can't work with swap enabled
   shell: |
     swapoff -a
  
 - name: Disable SWAP in fstab
   replace:
     path: /etc/fstab
     regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
     replace: '# \1'

 - name: Add the {{ item }} module
   #community.general.modprobe:
   modprobe:
     name: "{{ item }}"
     state: present
   loop: "{{ kernel_modules }}"

 - name: Setting some settings to sysctl
   ansible.builtin.blockinfile:
     path: /etc/sysctl.d/kubernetes.conf
     create: true
     block: |
       net.bridge.bridge-nf-call-ip6tables = 1
       net.bridge.bridge-nf-call-iptables = 1
       net.ipv4.ip_forward = 1
   notify: 
   - sysctl restart